<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDnRaDnD\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDnRaDnD/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDnRaDnD.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDnRaDnD\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerDnRaDnD\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'DnRaDnD',
    'container.build_id' => '497464e9',
    'container.build_time' => 1690811364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDnRaDnD');
