<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWEh6mHO\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEh6mHO/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWEh6mHO.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWEh6mHO\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerWEh6mHO\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'WEh6mHO',
    'container.build_id' => '22e01e41',
    'container.build_time' => 1690875559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEh6mHO');
