<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM2G4HLd\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM2G4HLd/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM2G4HLd.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM2G4HLd\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerM2G4HLd\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'M2G4HLd',
    'container.build_id' => '22a9387e',
    'container.build_time' => 1690815014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM2G4HLd');
