<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9OJns4K\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9OJns4K/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/Container9OJns4K.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\Container9OJns4K\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \Container9OJns4K\Shopware_Core_KernelProdContainer([
    'container.build_hash' => '9OJns4K',
    'container.build_id' => '2546224d',
    'container.build_time' => 1690813555,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9OJns4K');
